/**
 * Espejo de sorby_bot_wa/utils/utils-google/sheets/columnasMovimientos.js (ORDEN_DEFAULT y labels).
 * Si cambian las columnas en backend, actualizar aquí.
 */
export const KEY_ID = "id";

/** Orden por defecto de columnas en la planilla de movimientos (Google Sheet). */
export const ORDEN_DEFAULT = [
  KEY_ID,
  "fecha_factura",
  "ingreso",
  "egreso",
  "total",
  "tc",
  "observacion",
  "type",
  "user_phone",
  "moneda",
  "nombre_proveedor",
  "categoria",
  "subcategoria",
  "status",
  "estado",
  "medio_pago",
  "tipo_factura",
  "total_original",
  "extra",
  "proyecto_id",
  "proyecto",
  "codigo_operacion",
  "etapa",
  "cuenta",
  "subtotal_usd_blue",
  "total_usd_blue",
  "subtotal_cac",
  "total_cac",
  "subtotal",
  "impuestos",
];

/** Label por defecto por key (encabezado técnico / histórico). */
export const LABEL_DEFAULT_POR_KEY = {
  id: "id",
  fecha_factura: "fecha_factura",
  ingreso: "ingreso",
  egreso: "egreso",
  total: "total",
  tc: "tc",
  observacion: "observacion",
  type: "type",
  user_phone: "user_phone",
  moneda: "moneda",
  nombre_proveedor: "nombre_proveedor",
  categoria: "categoria",
  subcategoria: "subcategoria",
  status: "status",
  estado: "estado",
  medio_pago: "medio_pago",
  tipo_factura: "tipo_factura",
  total_original: "total_original",
  extra: "extra",
  proyecto_id: "proyecto_id",
  proyecto: "proyecto",
  codigo_operacion: "codigo_operacion",
  etapa: "etapa",
  cuenta: "cuenta",
  subtotal_usd_blue: "subtotal_usd_blue",
  total_usd_blue: "total_usd_blue",
  subtotal_cac: "subtotal_cac",
  total_cac: "total_cac",
  subtotal: "subtotal",
  impuestos: "impuestos",
};

/** Título legible para la UI (opcional). */
export const LABEL_UI_POR_KEY = {
  id: "ID",
  fecha_factura: "Fecha factura",
  ingreso: "Ingreso",
  egreso: "Egreso",
  total: "Total",
  tc: "Tipo de cambio",
  observacion: "Observación",
  type: "Tipo",
  user_phone: "Teléfono usuario",
  moneda: "Moneda",
  nombre_proveedor: "Proveedor",
  categoria: "Categoría",
  subcategoria: "Subcategoría",
  status: "Estado fila",
  estado: "Estado",
  medio_pago: "Medio de pago",
  tipo_factura: "Tipo factura",
  total_original: "Total original",
  extra: "Extra / tags",
  proyecto_id: "ID proyecto",
  proyecto: "Proyecto",
  codigo_operacion: "Código operación",
  etapa: "Etapa",
  cuenta: "Cuenta interna",
  subtotal_usd_blue: "Subtotal USD",
  total_usd_blue: "Total USD",
  subtotal_cac: "Subtotal CAC",
  total_cac: "Total CAC",
  subtotal: "Subtotal",
  impuestos: "Impuestos",
};
